[book]
authors = []
language = "en"
multilingual = false
src = "./docs_src"
title = "Fundoc"

[build]
build-dir = "./docs"
create-missing = true
extra-watch-dirs = []
use-default-preprocessors = true

[preprocessor.mermaid]
command = "./target/debug/fundoc -e"
